### ISSUE TITLE
unexpected end of stream

### ISSUE THREAD

**Issue by pinksy** [gdaws/node-stomp#32]
I am frequently getting an "unexpected end of stream" error. What might be the cause of this and how can I better debug it? I see it comes from IncomingFrameStream.js

**Comment by gdaws** [comment]
The error is caused by the server disconnecting before it finishes sending a frame. 

Once you find out how to can reproduce the error instantly, debug it by inspecting the captured network traffic and have trace debug messages enabled on node's net module (use NODE_DEBUG=net environment variable).

Some questions on your environment:

1. When is the error occurring: after connect is called, after send, during subscribe or after disconnect?
2. Is heart-beating enabled?
3. Which version of node is running?
4. Which message broker software is running and what version?

**Comment by pinksy** [comment]
Thank you for replying, and sorry for my slow reply back. Thank you Graham. It's an awesome library :)

The problem seems to be happening less often now, but I don't think it's anything I've done. However, I do see fairly frequent occurrences of "connection ended without disconnect receipt", mainly when I reconnect a durable topic subscription (by sending 'activemq.subscriptionName: foo' in the subscribe headers object that's passed to Client.subscribe) and there are a backlog of messages to catch up on. 

I do not have heart-beating enabled (should I?). 
I am running on Node V4.1.1. 
The broker is ActiveMQ 5.10.0.

**Comment by sebastienroul** [comment]
Had the same problem.

In my case : "unexpected end of stream" mean the other part (ActiveMQ) closed the connection.
Then after a while in ActiveMQ's log, I had 2 errors : 
  * java.io.IOException: Frame size of 1076 MB larger than max allowed 100 MB | org.apache.activemq.broker.TransportConnection.Transport - I fixed it, but new one appeared
  * java.io.IOException: Unknown data type: 69

Anyway, after another while I discovered that the instance of ActiveMQ was not well configured for STOMP : See http://activemq.apache.org/stomp.html

Then everythings works like a charm in production env.

Hope it helps.
