### ISSUE TITLE
Throughput drop with JMS MapMessage to Text transformation in STOMP consumer

### ISSUE THREAD

**Issue by choudhary001** [gdaws/node-stomp#42]
Hi,
I am trying to measure throughput for my use-case and noticed this strange thing:

With text messages from a java producer, the nodejs consumer is able to consumer messages at 10 Kmsgs/sec without any pending acks. 
However, the same nodejs consumer with exact same code (except the transformation header "transformation":jms-map-json during subscription) is able to consumer only 500 msgs/sec. I see lot of pending acks on broker. 

What could the reason that library is able to send acks faster for Text messages than map messages which is causing throughput drop.

I know for sure from jconsole stats that the broker has messages in pending queue and is not sending them because of pending unacknowledgements.

Do you have any idea why this difference is there?

Thanks,
Abhishek

**Comment by gdaws** [comment]
The transformation header has no meaning in STOMP and its presence in a message won't cause any extra processing for a STOMP client.

The cause of the throughput drop could be that the message broker is slower at sending messages to a subscriber because there's a significant performance cost to using the jms-map-json transformation. 

Have you measured the rate of incoming messages or the rate of ACK send on the subscription client?
