### ISSUE TITLE
Published version out of sync with repo?

### ISSUE THREAD

**Issue by pschuegr** [gdaws/node-stomp#57]
Hi,

I see the latest published version is 0.24.0 but this repo only has 0.23.0.  Has it been published from another repo?

Thanks!

**Comment by gdaws** [comment]
No it was published from this repo. The 0.24.0 npm package was published from a checkout of tag 0.24.0. 

What might have have caused confusion is the repo's releases page has the 0.24.0 tag listed, but it is displayed less prominently than 0.23.0 and isn't labelled as a "release" because it lacks release notes.
