### ISSUE TITLE
client handles errors differently when given heartbeat 0,0 vs 5000,5000

### ISSUE THREAD

**Issue by mateodelnorte** [gdaws/node-stomp#62]
It seems the stompit client does not handle errors the same way when configured to `heart-beat` at 0,0 vs 5000,5000. With numbers larger than 0, the client correctly emits an error which can be caught and used to reconnect. It seems with 0,0 the error will automatically go to uncaughtException. 

The code I'm using looks similar to the following: 
```
    const manager = new stompit.ConnectFailover(servers, reconnectOptions);

    manager.connect((err, client, reconnect) => {

      if (err) {
        // terminal error, given up reconnecting
        this.emit('error', err);
      }
      
      console.log('connected to bus');

      client.on('error', (err) => {

        console.log('stompit client error (reconnecting now): ', err);

        this.reconnecting = true;
        
        reconnect();

      });

      this.client = client;

      if (this.reconnecting) {
        console.log('reconnected to bus');

        // replay and sends that did not yet reach the broker
        console.log(`re-sending ${this.pendingSends.size} _sends`);
        this.pendingSends.forEach((pendingSend) => {
          setTimeout(pendingSend, 500);
        })
        console.log(`reapplying ${this.subscriptions.length} subscriptions`);
        // resubscribe to any disconnected subscriptions now that we've reconnected
        this.subscriptions.forEach((subscription) => {
          subscription();
        });
      } else {
        this.emit('connected');
      }
      
      cb();

    });
```
In both scenarios, I see `console.log('stompit client error (reconnecting now): ', err);` logged. But with 0,0 I immediately see a log statement from my `process.on('uncaughtException` and the additional reconnect logic never gets a chance to run. With 5000,5000 the reconnect logic works as expected.

**Comment by gdaws** [comment]
If you see `console.log('stompit client error (reconnecting now): ', err);` then the reconnect function is definitely called. Are you sure the uncaught exception is not caused by `this.emit('error', err);`?

The stompit client has the same expected usage in both scenarios. 

The implementation of Client and ConnectFailover listen to catch errors events from their underlying objects and this behaviour isn't changed by heart-beating being enabled or not.

To help debugging we need details on the uncaught exception. What is the error message and what is the call stack on the Error object and the call stack of the uncaughtException handler?
